#!/usr/bin/env python3
"""
CFD Visualization Script
========================

Creates static plots and animations from VTK output files generated by CFD simulations.

Usage:
    python visualize_cfd.py [options]

    # Create static PNG plots
    python visualize_cfd.py --static

    # Create animated GIFs
    python visualize_cfd.py --animate

    # Create both (default)
    python visualize_cfd.py --all

    # Visualize specific field
    python visualize_cfd.py --field pressure --animate
"""

from typing import Dict, Tuple

import matplotlib
import numpy as np
from numpy.typing import NDArray

matplotlib.use('Agg')  # Use non-interactive backend
import argparse
import os
import sys

import matplotlib.animation as animation
import matplotlib.pyplot as plt

# Add parent directory to path for config import
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import ANIMATIONS_DIR, DATA_DIR, PLOTS_DIR, ensure_dirs, find_vtk_files
from vtk_reader import read_vtk_file as _read_vtk_file


def extract_iteration_from_filename(filename: str, fallback: int) -> int:
    """Extract iteration number from VTK filename.

    Expects filenames like 'flow_field_0100.vtk' where the iteration
    number is the last numeric segment before the extension.

    Args:
        filename: Path to the VTK file.
        fallback: Value to return if extraction fails.

    Returns:
        Extracted iteration number, or fallback value.
    """
    try:
        return int(os.path.basename(filename).split('_')[-1].split('.')[0])
    except ValueError:
        return fallback


def read_vtk_file(filename: str) -> Tuple[NDArray, NDArray, Dict[str, NDArray]]:
    """Read a VTK structured points file and extract data.

    Args:
        filename: Path to the VTK file.

    Returns:
        Tuple of (X, Y, data_fields) where X and Y are coordinate meshgrids
        and data_fields is a dict mapping field names to 2D arrays.
    """
    data = _read_vtk_file(filename)
    if data is None:
        raise ValueError(f"Could not read VTK file: {filename}")
    return data.X, data.Y, data.fields


def create_velocity_magnitude(u, v):
    """Calculate velocity magnitude from u and v components"""
    return np.sqrt(u**2 + v**2)


# =============================================================================
# Static Plot Functions
# =============================================================================

def create_static_plot(X, Y, data, title, output_file, cmap='viridis', label='Value'):
    """Create a single static contour plot"""
    plt.figure(figsize=(10, 6))

    contour = plt.contourf(X, Y, data, levels=20, cmap=cmap)
    plt.colorbar(contour, label=label)
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.title(title)
    plt.grid(True, alpha=0.3)

    plt.savefig(output_file, dpi=150, bbox_inches='tight')
    plt.close()

    print(f"  Saved: {output_file}")


def create_static_plots(vtk_files, field=None):
    """Create static PNG plots from VTK files"""
    print("\nCreating static plots...")

    for filename in vtk_files:
        print(f"Processing {os.path.basename(filename)}...")

        try:
            X, Y, data_fields = read_vtk_file(filename)
            base_name = os.path.splitext(os.path.basename(filename))[0]

            if field:
                # Plot specific field
                if field == 'velocity_magnitude' and 'u' in data_fields and 'v' in data_fields:
                    data = create_velocity_magnitude(data_fields['u'], data_fields['v'])
                    output_file = str(PLOTS_DIR / f"{base_name}_velocity_magnitude.png")
                    create_static_plot(X, Y, data, f'Velocity Magnitude - {base_name}',
                                      output_file, 'viridis', 'Velocity Magnitude')
                elif field in data_fields:
                    output_file = str(PLOTS_DIR / f"{base_name}_{field}.png")
                    create_static_plot(X, Y, data_fields[field], f'{field} - {base_name}',
                                      output_file, 'viridis', field)
                else:
                    print(f"  Warning: Field '{field}' not found")
            else:
                # Plot all available fields
                if 'u' in data_fields and 'v' in data_fields:
                    vel_mag = create_velocity_magnitude(data_fields['u'], data_fields['v'])
                    output_file = str(PLOTS_DIR / f"{base_name}_velocity_magnitude.png")
                    create_static_plot(X, Y, vel_mag, f'Velocity Magnitude - {base_name}',
                                      output_file, 'viridis', 'Velocity Magnitude')

                if 'p' in data_fields:
                    output_file = str(PLOTS_DIR / f"{base_name}_pressure.png")
                    create_static_plot(X, Y, data_fields['p'], f'Pressure - {base_name}',
                                      output_file, 'coolwarm', 'Pressure')

        except Exception as e:
            print(f"  Error processing {filename}: {e}")

    print(f"\nStatic plots saved to {PLOTS_DIR}")


# =============================================================================
# Animation Functions
# =============================================================================

def animate_field(vtk_files, field_name='velocity_magnitude', output_prefix=None):
    """Create animation of a specific field

    Args:
        vtk_files: List of VTK files to animate
        field_name: Field to animate (default: velocity_magnitude)
        output_prefix: Prefix for output filename (default: 'cfd_animation')
    """
    print(f"\nCreating {field_name} animation...")

    # Read all files and extract data
    frames_data = []
    times = []
    X, Y = None, None

    for filename in sorted(vtk_files):
        try:
            X, Y, data_fields = read_vtk_file(filename)

            if field_name == 'velocity_magnitude':
                if 'u' in data_fields and 'v' in data_fields:
                    field_data = create_velocity_magnitude(data_fields['u'], data_fields['v'])
                else:
                    continue
            elif field_name in data_fields:
                field_data = data_fields[field_name]
            else:
                continue

            frames_data.append(field_data)
            times.append(extract_iteration_from_filename(filename, len(times)))

        except Exception as e:
            print(f"  Error reading {filename}: {e}")
            continue

    if not frames_data:
        print(f"  No valid data found for {field_name}!")
        return None

    print(f"  Found {len(frames_data)} frames")

    # Set up the figure and axis
    fig, ax = plt.subplots(figsize=(12, 6))

    # Calculate global min/max for consistent colormap
    vmin = min(np.min(frame) for frame in frames_data)
    vmax = max(np.max(frame) for frame in frames_data)

    # Create initial plot
    im = ax.imshow(frames_data[0], extent=[X.min(), X.max(), Y.min(), Y.max()],
                   origin='lower', aspect='auto', vmin=vmin, vmax=vmax, cmap='viridis')

    # Add colorbar
    cbar = plt.colorbar(im, ax=ax)
    cbar.set_label(field_name.replace('_', ' ').title())

    # Set labels
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_title(f'CFD Simulation - {field_name.replace("_", " ").title()}')

    # Add iteration counter
    time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes,
                       bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

    def animate(frame):
        im.set_array(frames_data[frame])
        time_text.set_text(f'Iteration: {times[frame]}')
        return [im, time_text]

    # Create animation
    anim = animation.FuncAnimation(fig, animate, frames=len(frames_data),
                                 interval=200, blit=True, repeat=True)

    # Save animation
    prefix = output_prefix or 'cfd_animation'
    output_file = str(ANIMATIONS_DIR / f'{prefix}_{field_name}.gif')
    print(f"  Saving animation to {output_file}...")
    anim.save(output_file, writer='pillow', fps=5)
    print("  Animation saved!")

    plt.close()
    return anim


def create_streamline_animation(vtk_files):
    """Create streamline animation"""
    print("\nCreating streamline animation...")

    frames_data = []
    times = []
    X, Y = None, None

    for filename in sorted(vtk_files):
        try:
            X, Y, data_fields = read_vtk_file(filename)

            if 'u' in data_fields and 'v' in data_fields:
                frames_data.append((data_fields['u'], data_fields['v']))
                times.append(extract_iteration_from_filename(filename, len(times)))
        except Exception as e:
            print(f"  Error reading {filename}: {e}")
            continue

    if not frames_data:
        print("  No valid velocity data found!")
        return None

    print(f"  Found {len(frames_data)} frames")

    fig, ax = plt.subplots(figsize=(12, 6))

    # For streamplot, we need 1D arrays for x and y coordinates
    x = X[0, :] if len(X.shape) == 2 else X
    y = Y[:, 0] if len(Y.shape) == 2 else Y

    def animate(frame):
        ax.clear()
        u_frame, v_frame = frames_data[frame]

        # Create streamlines - streamplot expects 1D x, y and 2D u, v
        # u and v should have shape (len(y), len(x))
        # Transpose if necessary to match the expected shape
        if u_frame.shape == (len(x), len(y)):
            u_frame = u_frame.T
            v_frame = v_frame.T
        elif u_frame.shape != (len(y), len(x)):
            print(f"Warning: Frame {frame} shape {u_frame.shape} doesn't match grid ({len(y)}, {len(x)})")

        # Calculate speed for coloring
        speed = np.sqrt(u_frame**2 + v_frame**2)

        ax.streamplot(x, y, u_frame, v_frame, color=speed, cmap='viridis', density=1.5, linewidth=0.5)

        ax.set_xlabel('X')
        ax.set_ylabel('Y')
        ax.set_title(f'CFD Streamlines - Iteration: {times[frame]}')
        ax.set_xlim(x.min(), x.max())
        ax.set_ylim(y.min(), y.max())

    anim = animation.FuncAnimation(fig, animate, frames=len(frames_data),
                                 interval=200, repeat=True)

    output_file = str(ANIMATIONS_DIR / 'cfd_streamlines.gif')
    print(f"  Saving streamline animation to {output_file}...")
    anim.save(output_file, writer='pillow', fps=5)
    print("  Animation saved!")

    plt.close()
    return anim


def create_animations(vtk_files, field=None, include_streamlines=False, output_prefix=None):
    """Create animated GIFs from VTK files

    Args:
        vtk_files: List of VTK files to animate
        field: Specific field to animate (default: all standard fields)
        include_streamlines: Whether to create streamline animation
        output_prefix: Prefix for output filenames (e.g., 'high_reynolds')
    """
    if field:
        animate_field(vtk_files, field, output_prefix=output_prefix)
    else:
        # Create all standard animations
        animate_field(vtk_files, 'velocity_magnitude', output_prefix=output_prefix)
        animate_field(vtk_files, 'p', output_prefix=output_prefix)
        if include_streamlines:
            try:
                create_streamline_animation(vtk_files)
            except Exception as e:
                print(f"  Streamline animation failed: {e}")

    print(f"\nAnimations saved to {ANIMATIONS_DIR}")


# =============================================================================
# Main
# =============================================================================

def main():
    """Main function"""
    parser = argparse.ArgumentParser(
        description='Create visualizations from CFD VTK files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python visualize_cfd.py --static          # Create PNG plots
  python visualize_cfd.py --animate         # Create GIF animations
  python visualize_cfd.py --all             # Create both (default)
  python visualize_cfd.py --field p         # Only visualize pressure field
  python visualize_cfd.py --latest --static # Plot only the latest VTK file
        """
    )

    parser.add_argument('--static', '-s', action='store_true',
                       help='Create static PNG plots')
    parser.add_argument('--animate', '-a', action='store_true',
                       help='Create animated GIFs')
    parser.add_argument('--all', action='store_true',
                       help='Create both static and animated outputs (default)')
    parser.add_argument('--field', '-f', type=str, default=None,
                       help='Specific field to visualize (velocity_magnitude, p, u, v)')
    parser.add_argument('--input', '-i', type=str, default=None,
                       help='Single VTK file to visualize')
    parser.add_argument('--latest', '-l', action='store_true',
                       help='Use only the most recent VTK file')

    args = parser.parse_args()

    # Ensure output directories exist
    ensure_dirs()

    # Determine which VTK files to use
    if args.input:
        if not os.path.exists(args.input):
            print(f"Error: File not found: {args.input}")
            return
        vtk_files = [args.input]
    else:
        vtk_files = find_vtk_files()
        if not vtk_files:
            print(f"No VTK files found in {DATA_DIR}")
            print("Set CFD_VIZ_DATA_DIR environment variable to specify a different location.")
            return
        vtk_files = [str(f) for f in vtk_files]

        if args.latest:
            vtk_files = [max(vtk_files, key=os.path.getmtime)]

    print(f"Found {len(vtk_files)} VTK file(s)")

    # Determine what to create (default: do both if neither specified)
    do_both = not args.static and not args.animate
    do_static = args.static or args.all or do_both
    do_animate = args.animate or args.all or do_both

    if do_static:
        create_static_plots(vtk_files, args.field)

    if do_animate and len(vtk_files) > 1:
        create_animations(vtk_files, args.field)
    elif do_animate and len(vtk_files) == 1:
        print("\nSkipping animations (need multiple VTK files for animation)")

    print("\nVisualization complete!")


if __name__ == "__main__":
    main()
